### ISSUE TITLE
Error when script is ran in the current state of the repository

### ISSUE THREAD

**Issue by j-tesla** [thealphadollar/GSoCOrgFrequency#4]
The following error is popping when the src in run in the current state of repo. Although, when the script is run again, error disappears.
```
DEBUG: Failed to load 2021 data from CSV file
DEBUG: Scraping data for 2021...
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "src/__main__.py", line 27, in <module>
    main()
  File "src/__main__.py", line 17, in main
    save_csv(year_data, year)
  File "src/utils.py", line 35, in save_csv
    writer = DictWriter(f, values[0].keys())
IndexError: list index out of range
```

**Comment by thealphadollar** [comment]
I think the error exists as the archive for the year 2021 has not been generated. It should be easy to fix with a try-catch or updating the logic to handle not yet built archives.
